#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Where everything lives. The Debian rootfs is an ordinary directory from
# Termux's side, so the wizard can write .env.local into it directly while
# running every build command inside the container.
DEBIAN_ROOT="${PREFIX:-/data/data/com.termux/files/usr}/var/lib/proot-distro/installed-rootfs/debian"
APP_IN_DEBIAN="/root/morning-briefing"
APP_DIR="$DEBIAN_ROOT$APP_IN_DEBIAN"
ENV_FILE="$APP_DIR/.env.local"
REPO="https://github.com/zlipson1999/morning-briefing"

# Run a command inside the Debian container.
in_debian() { proot-distro login debian -- bash -lc "$1"; }

# Open a URL using Termux's opener when the Android one is installed.
open_android() {
  if command -v termux-open-url >/dev/null 2>&1; then termux-open-url "$1"
  else note "open this in Chrome: $1"; fi
}

banner "Miles on Android — standalone, no PC"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Termux: check the ground"
say "Miles needs a glibc Linux to build. Termux itself is Bionic, and Next.js"
say "ships no Android binary, so we install Debian inside Termux and work there."
case "${PREFIX:-}" in
  *com.termux*) say "Running inside Termux. Good." ;;
  *) warn "This does not look like Termux. Run it from the Termux app."; exit 1 ;;
esac
arch=$(uname -m)
say "Architecture: $arch"
[[ "$arch" == "aarch64" ]] || warn "Expected aarch64; a 32-bit device will not work."
note "If you installed Termux from the Play Store, uninstall it and use the"
note "F-Droid build — the Play Store one is abandoned and too old for this."
confirm "Continue?" || exit 1
say "Installing proot-distro…"
pkg install -y proot-distro >/dev/null 2>&1 || pkg install -y proot-distro
say "proot-distro ready."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Debian: the Linux that can build Next.js"
if [[ -d "$DEBIAN_ROOT" ]]; then
  say "Debian is already installed. Keeping it."
else
  say "Installing Debian. This downloads a few hundred MB — give it a minute."
  proot-distro install debian
fi
in_debian "cat /etc/debian_version" | sed 's/^/  Debian /'
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Node 22 inside Debian"
say "Next 16 needs Node 20.9 or newer. Debian's own package is Node 18, which"
say "would fail at build time, so we take Node 22 from NodeSource instead."
current=$(in_debian "node -v 2>/dev/null || true" | tr -d '\r')
if [[ "$current" =~ ^v(2[2-9]|[3-9][0-9]) ]]; then
  say "Node $current is already installed. Skipping."
else
  say "Installing curl, git and Node 22 — a few minutes."
  in_debian "apt-get update -qq && apt-get install -y -qq curl ca-certificates git"
  in_debian "curl -fsSL https://deb.nodesource.com/setup_22.x | bash - >/dev/null"
  in_debian "apt-get install -y -qq nodejs"
fi
say "node $(in_debian 'node -v' | tr -d '\r'), npm $(in_debian 'npm -v' | tr -d '\r')"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Get Miles"
if [[ -d "$APP_DIR/.git" ]]; then
  say "Miles is already cloned. Pulling the latest."
  in_debian "cd $APP_IN_DEBIAN && git pull --ff-only"
else
  say "Cloning $REPO"
  in_debian "git clone $REPO $APP_IN_DEBIAN"
fi
say "At $APP_IN_DEBIAN inside Debian."
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Credentials"
say "Miles runs at http://localhost:3000 on this phone, which is the very"
say "redirect URI your existing Google client already allows — so the client id"
say "and secret from your PC's .env.local work here unchanged."
note "Leave any of these blank to skip: the dashboard still runs without them."
if [[ -z "$(grep -E '^SESSION_SECRET=.+' "$ENV_FILE" 2>/dev/null || true)" ]]; then
  write_env SESSION_SECRET "$(head -c 32 /dev/urandom | base64 | tr -d '\n=' )"
  note "generated a SESSION_SECRET so the Google grant survives a restart"
fi
ask GOOGLE_CLIENT_ID "GOOGLE_CLIENT_ID (from your PC's .env.local):"
[[ -n "$GOOGLE_CLIENT_ID" ]] && write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
ask_secret GOOGLE_CLIENT_SECRET "GOOGLE_CLIENT_SECRET:"
[[ -n "$GOOGLE_CLIENT_SECRET" ]] && write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
ask_secret ANTHROPIC_API_KEY "ANTHROPIC_API_KEY (optional, writes the spoken briefing):"
[[ -n "$ANTHROPIC_API_KEY" ]] && write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
say ""
say "Chat needs Ollama. A later stage can install it on this phone so Ask Miles"
say "works with no PC at all; if you would rather borrow your PC's, give its"
say "address here. Blank is fine either way."
ask OLLAMA_URL "OLLAMA_URL (e.g. http://192.168.1.20:11434, or blank):"
[[ -n "$OLLAMA_URL" ]] && write_env OLLAMA_URL "$OLLAMA_URL"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Install and build"
warn "This is the slow part: several minutes, and the phone will get warm."
note "Keep the screen on and Termux in the foreground until it finishes."
confirm "Start the build?" || exit 1
say "Installing dependencies…"
in_debian "cd $APP_IN_DEBIAN && npm install --no-audit --no-fund"
say "Building…"
in_debian "cd $APP_IN_DEBIAN && NODE_OPTIONS=--max-old-space-size=2048 npm run build"
say "Built."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Chat on the phone itself (optional)"
ONDEVICE_LLM=0
say "Ollama can run here too, which makes Ask Miles work with no PC anywhere"
say "in the picture — private, offline, and yours alone."
note "It downloads a model of a gigabyte or more, answers slowly next to a PC,"
note "and warms the phone while it is thinking. A small model is the point:"
note "the default gemma4:e2b is sized for exactly this."
if confirm "Install Ollama on this phone?"; then
  write_env OLLAMA_URL "http://127.0.0.1:11434"
  say "Installing Ollama and pulling the model — the long part is the download."
  if in_debian "cd $APP_IN_DEBIAN && bash scripts/setup-local-llm.sh"; then
    ONDEVICE_LLM=1
    say "On-device chat is ready."
  else
    warn "That did not finish. Miles still runs; Ask Miles will report Ollama as"
    warn "unreachable until you re-run this wizard or the script by hand."
  fi
else
  say "Skipped. Ask Miles stays off unless OLLAMA_URL points somewhere."
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Start Miles and open it"
if [[ "$ONDEVICE_LLM" == "1" ]]; then
  RUN_CMD="cd $APP_IN_DEBIAN && (ollama serve >/tmp/ollama.log 2>&1 &) && sleep 2 && npm run start"
  note "Ollama starts alongside Miles: a proot session takes its processes with"
  note "it when it ends, so both belong in the one command."
else
  RUN_CMD="cd $APP_IN_DEBIAN && npm run start"
fi
say "Starting the server…"
proot-distro login debian -- bash -lc "$RUN_CMD" >/dev/null 2>&1 &
for _ in $(seq 1 40); do
  sleep 1
  curl -sf http://localhost:3000 >/dev/null 2>&1 && break
done
if curl -sf http://localhost:3000 >/dev/null 2>&1; then
  say "Miles is answering on http://localhost:3000"
else
  warn "It did not answer in 40s. Run it in the foreground to see why:"
  note "proot-distro login debian -- bash -lc '$RUN_CMD'"
fi
open_android "http://localhost:3000"
step "In Chrome: ⋮ menu → Add to Home screen."
note "localhost counts as a secure origin, so the microphone, Hey Miles and"
note "notifications all work here without any HTTPS setup."
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Keep it running"
if command -v termux-wake-lock >/dev/null 2>&1; then
  termux-wake-lock && say "Wake lock on: Android will not sleep Termux."
else
  SKIPPED+=("termux-wake-lock (install Termux:API, then run it before starting Miles)")
  warn "termux-wake-lock missing — Android will kill Miles when the screen sleeps."
fi
step "Android settings → Apps → Termux → Battery → Unrestricted."
step "Install the Termux:Boot add-on from F-Droid to start Miles after a reboot."
say ""
say "To start Miles again later, one line in Termux:"
note "  termux-wake-lock; proot-distro login debian -- bash -lc '$RUN_CMD'"
say "To update it later:"
note "  proot-distro login debian -- bash -lc 'cd $APP_IN_DEBIAN && git pull && npm install && npm run build'"
pause

finish
note "Miles is running on this phone alone. No PC, no Tailscale, nothing on the network."
